export const mockStudent = {
  id: '2024001',
  name: 'João Silva',
  initials: 'JS',
  email: 'joao.silva@btcp.edu.br',
  phone: '(11) 99234-5678',
  ra: '2024001',
  course: 'Bacharelado em Teologia',
  semester: '3º Semestre',
  status: 'Ativo',
  enrollmentDate: '2024-02-01',
  cpf: '***.***.***-**',
  birthDate: '15/04/1995',
  address: 'Rua das Flores, 123 – São Paulo, SP',
  photo: null,
}

export const mockBibleVerses = [
  {
    text: 'Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna.',
    reference: 'João 3:16',
  },
  {
    text: 'O Senhor é o meu pastor; nada me faltará. Ele me faz repousar em pastos verdejantes.',
    reference: 'Salmos 23:1-2',
  },
  {
    text: 'Posso tudo naquele que me fortalece.',
    reference: 'Filipenses 4:13',
  },
  {
    text: 'Confia no Senhor de todo o teu coração e não te apoies na tua própria prudência.',
    reference: 'Provérbios 3:5',
  },
  {
    text: 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça.',
    reference: '2 Timóteo 3:16',
  },
]

export const mockCourses = [
  {
    id: 1,
    name: 'Antigo Testamento I',
    code: 'AT-101',
    professor: 'Rev. Carlos Mendes',
    credits: 4,
    grade1: 8.5,
    grade2: 9.0,
    grade3: null,
    absences: 2,
    totalClasses: 30,
    maxAbsences: 7,
    status: 'Em andamento',
    schedule: 'Seg/Qua – 08:00',
    room: 'Sala 101',
  },
  {
    id: 2,
    name: 'Novo Testamento I',
    code: 'NT-101',
    professor: 'Dr. Paulo Ferreira',
    credits: 4,
    grade1: 7.8,
    grade2: 8.5,
    grade3: null,
    absences: 1,
    totalClasses: 30,
    maxAbsences: 7,
    status: 'Em andamento',
    schedule: 'Ter/Qui – 10:00',
    room: 'Auditório',
  },
  {
    id: 3,
    name: 'Teologia Sistemática I',
    code: 'TS-201',
    professor: 'Rev. Marcos Rodrigues',
    credits: 4,
    grade1: 9.2,
    grade2: 9.5,
    grade3: null,
    absences: 0,
    totalClasses: 30,
    maxAbsences: 7,
    status: 'Em andamento',
    schedule: 'Seg/Qua – 14:00',
    room: 'Sala 201',
  },
  {
    id: 4,
    name: 'Hermenêutica',
    code: 'HM-201',
    professor: 'Dr. André Lima',
    credits: 3,
    grade1: 8.0,
    grade2: 7.5,
    grade3: null,
    absences: 3,
    totalClasses: 30,
    maxAbsences: 7,
    status: 'Em andamento',
    schedule: 'Ter/Qui – 08:00',
    room: 'Sala 103',
  },
  {
    id: 5,
    name: 'História da Igreja',
    code: 'HI-101',
    professor: 'Prof. Roberto Alves',
    credits: 3,
    grade1: 8.8,
    grade2: 9.0,
    grade3: null,
    absences: 1,
    totalClasses: 30,
    maxAbsences: 7,
    status: 'Em andamento',
    schedule: 'Sex – 08:00',
    room: 'Sala 104',
  },
  {
    id: 6,
    name: 'Homilética',
    code: 'HO-301',
    professor: 'Rev. Tiago Santos',
    credits: 3,
    grade1: 9.0,
    grade2: 8.5,
    grade3: null,
    absences: 0,
    totalClasses: 30,
    maxAbsences: 7,
    status: 'Em andamento',
    schedule: 'Qua – 14:00',
    room: 'Auditório',
  },
]

export const mockFinancial = {
  status: 'Em dia',
  nextDueDate: '10/06/2026',
  monthlyFee: 350.0,
  balance: 0,
  payments: [
    {
      id: 1,
      month: 'Janeiro 2026',
      amount: 350.0,
      dueDate: '10/01/2026',
      paidDate: '08/01/2026',
      status: 'Pago',
      method: 'PIX',
    },
    {
      id: 2,
      month: 'Fevereiro 2026',
      amount: 350.0,
      dueDate: '10/02/2026',
      paidDate: '09/02/2026',
      status: 'Pago',
      method: 'Boleto',
    },
    {
      id: 3,
      month: 'Março 2026',
      amount: 350.0,
      dueDate: '10/03/2026',
      paidDate: '10/03/2026',
      status: 'Pago',
      method: 'PIX',
    },
    {
      id: 4,
      month: 'Abril 2026',
      amount: 350.0,
      dueDate: '10/04/2026',
      paidDate: '07/04/2026',
      status: 'Pago',
      method: 'PIX',
    },
    {
      id: 5,
      month: 'Maio 2026',
      amount: 350.0,
      dueDate: '10/05/2026',
      paidDate: '10/05/2026',
      status: 'Pago',
      method: 'Boleto',
    },
    {
      id: 6,
      month: 'Junho 2026',
      amount: 350.0,
      dueDate: '10/06/2026',
      paidDate: null,
      status: 'Pendente',
      method: null,
    },
  ],
}

export const mockCalendarEvents = [
  { id: 1, title: 'Prova – Antigo Testamento I', date: '2026-06-05', type: 'exam', time: '08:00' },
  { id: 2, title: 'Culto Estudantil', date: '2026-05-28', type: 'event', time: '19:00' },
  { id: 3, title: 'Entrega – Trabalho de Hermenêutica', date: '2026-06-10', type: 'deadline', time: '23:59' },
  { id: 4, title: 'Prova – Teologia Sistemática I', date: '2026-06-12', type: 'exam', time: '14:00' },
  { id: 5, title: 'Semana de Teologia', date: '2026-06-16', type: 'event', time: '09:00' },
  { id: 6, title: 'Feriado – Corpus Christi', date: '2026-06-19', type: 'holiday', time: 'Todo o dia' },
  { id: 7, title: 'Início do Recesso de Julho', date: '2026-07-01', type: 'academic', time: 'Todo o dia' },
  { id: 8, title: 'Confraternização dos Alunos', date: '2026-06-26', type: 'event', time: '18:00' },
  { id: 9, title: 'Prova – História da Igreja', date: '2026-06-08', type: 'exam', time: '08:00' },
  { id: 10, title: 'Prazo de Solicitação de Documentos', date: '2026-06-30', type: 'deadline', time: '17:00' },
]

export const mockDocuments = [
  { id: 1, name: 'Contrato de Matrícula', category: 'Contrato', date: '01/02/2026', size: '245 KB', status: 'Aprovado', type: 'pdf' },
  { id: 2, name: 'Histórico Escolar 2025', category: 'Acadêmico', date: '15/01/2026', size: '180 KB', status: 'Disponível', type: 'pdf' },
  { id: 3, name: 'Declaração de Matrícula', category: 'Acadêmico', date: '01/02/2026', size: '95 KB', status: 'Disponível', type: 'pdf' },
  { id: 4, name: 'RG (Documento Pessoal)', category: 'Pessoal', date: '10/01/2026', size: '520 KB', status: 'Aprovado', type: 'img' },
  { id: 5, name: 'CPF', category: 'Pessoal', date: '10/01/2026', size: '312 KB', status: 'Aprovado', type: 'pdf' },
  { id: 6, name: 'Certificado de Conclusão – Módulo 1', category: 'Certificado', date: '20/12/2025', size: '620 KB', status: 'Disponível', type: 'pdf' },
]

export const mockRequests = [
  {
    id: 1,
    protocol: 'REQ-2026-001',
    type: 'Declaração de Matrícula',
    subject: null,
    status: 'Concluído',
    createdAt: '20/01/2026',
    updatedAt: '22/01/2026',
    description: 'Solicitação de declaração para fins de comprovação junto ao empregador.',
  },
  {
    id: 2,
    protocol: 'REQ-2026-042',
    type: 'Revisão de Nota',
    subject: 'Hermenêutica',
    status: 'Em análise',
    createdAt: '01/05/2026',
    updatedAt: '01/05/2026',
    description: 'Solicito revisão da nota da Prova 2 da disciplina de Hermenêutica.',
  },
  {
    id: 3,
    protocol: 'REQ-2026-058',
    type: 'Trancamento de Disciplina',
    subject: 'Grego Bíblico I',
    status: 'Pendente',
    createdAt: '10/05/2026',
    updatedAt: '10/05/2026',
    description: 'Solicitação de trancamento por motivos de saúde (laudo médico em anexo).',
  },
]

export const mockMaterials = [
  { id: 1, course: 'Antigo Testamento I', type: 'pdf', title: 'Apostila – Introdução ao Pentateuco', date: '20/01/2026', size: '2.3 MB', professor: 'Rev. Carlos Mendes' },
  { id: 2, course: 'Antigo Testamento I', type: 'video', title: 'Aula 1 – Introdução ao AT', date: '22/01/2026', duration: '45 min', professor: 'Rev. Carlos Mendes' },
  { id: 3, course: 'Antigo Testamento I', type: 'pdf', title: 'Estudo de Gênesis 1-11', date: '29/01/2026', size: '1.5 MB', professor: 'Rev. Carlos Mendes' },
  { id: 4, course: 'Teologia Sistemática I', type: 'pdf', title: 'Fundamentos da Fé Cristã', date: '25/01/2026', size: '1.8 MB', professor: 'Rev. Marcos Rodrigues' },
  { id: 5, course: 'Teologia Sistemática I', type: 'audio', title: 'Podcast – Doutrina da Revelação', date: '28/01/2026', duration: '32 min', professor: 'Rev. Marcos Rodrigues' },
  { id: 6, course: 'Hermenêutica', type: 'pdf', title: 'Princípios de Interpretação Bíblica', date: '28/01/2026', size: '3.1 MB', professor: 'Dr. André Lima' },
  { id: 7, course: 'Novo Testamento I', type: 'video', title: 'Contexto Histórico do NT', date: '01/02/2026', duration: '38 min', professor: 'Dr. Paulo Ferreira' },
  { id: 8, course: 'Homilética', type: 'pdf', title: 'Como Preparar um Sermão Expositivo', date: '02/02/2026', size: '890 KB', professor: 'Rev. Tiago Santos' },
  { id: 9, course: 'Homilética', type: 'audio', title: 'Exemplo de Sermão – Rev. Tiago Santos', date: '05/02/2026', duration: '22 min', professor: 'Rev. Tiago Santos' },
  { id: 10, course: 'História da Igreja', type: 'pdf', title: 'Igreja Primitiva – Séculos I-III', date: '03/02/2026', size: '4.2 MB', professor: 'Prof. Roberto Alves' },
]

export const mockCheckins = [
  { id: 1, course: 'Antigo Testamento I', date: '22/05/2026', time: '07:58', professor: 'Rev. Carlos Mendes', status: 'Confirmado' },
  { id: 2, course: 'Teologia Sistemática I', date: '22/05/2026', time: '14:02', professor: 'Rev. Marcos Rodrigues', status: 'Confirmado' },
  { id: 3, course: 'Novo Testamento I', date: '21/05/2026', time: '10:05', professor: 'Dr. Paulo Ferreira', status: 'Confirmado' },
  { id: 4, course: 'Hermenêutica', date: '21/05/2026', time: '08:00', professor: 'Dr. André Lima', status: 'Confirmado' },
  { id: 5, course: 'Antigo Testamento I', date: '20/05/2026', time: '--:--', professor: 'Rev. Carlos Mendes', status: 'Ausente' },
  { id: 6, course: 'História da Igreja', date: '19/05/2026', time: '08:10', professor: 'Prof. Roberto Alves', status: 'Confirmado' },
  { id: 7, course: 'Homilética', date: '18/05/2026', time: '13:58', professor: 'Rev. Tiago Santos', status: 'Confirmado' },
]

export const mockUpcomingClasses = [
  { id: 1, course: 'Antigo Testamento I', professor: 'Rev. Carlos Mendes', time: '08:00 – 09:40', room: 'Sala 101', day: 'Hoje' },
  { id: 2, course: 'Teologia Sistemática I', professor: 'Rev. Marcos Rodrigues', time: '14:00 – 15:40', room: 'Sala 201', day: 'Hoje' },
  { id: 3, course: 'Novo Testamento I', professor: 'Dr. Paulo Ferreira', time: '10:00 – 11:40', room: 'Auditório', day: 'Amanhã' },
  { id: 4, course: 'Hermenêutica', professor: 'Dr. André Lima', time: '08:00 – 09:40', room: 'Sala 103', day: 'Amanhã' },
]

export const mockAnnouncements = [
  { id: 1, title: 'Boleto de Junho vence em 10/06', type: 'financial', date: '22/05/2026', priority: 'high' },
  { id: 2, title: 'Semana de Teologia – 16 a 20 de Junho', type: 'event', date: '20/05/2026', priority: 'medium' },
  { id: 3, title: 'Novo material em Antigo Testamento I', type: 'material', date: '19/05/2026', priority: 'low' },
  { id: 4, title: 'Prazo de entrega do trabalho de Hermenêutica: 10/06', type: 'academic', date: '18/05/2026', priority: 'high' },
]
